added issues and pullrequests lists for contributor
Hexlet/hexlet-friends pull request #148
Opened 2022-04-13 12:24 UTC by EvilMadSquirrel

Почему-то не работают сортировки и фильтры :( 
И если делать вкладками, как на главной странице, нужно немного времени, т.к. там есть JS - нужно понять, что он делает, и как его использовать :)

2022-05-06 13:29 UTC, mkaraev reviewed
@EvilMadSquirrel там был коммент, что не работают сортировки. Сейчас они работают?
А еще, я не вижу тестов к твоим вьюшкам. Это же новые вьюишки. Хорошо бы сделать тесты.

2022-05-07 14:32 UTC, antlu requested changes
Сортировка не работает, потому что views переопределяют метод get_queryset родительского класса.

2022-05-07 14:32 UTC, antlu commented on templates/contributor_issues.html
> +  {% include 'components/tables/contributor_issues.html' %}
Вряд ли стоит прятать список в компоненты. Он же не переиспользуется.

2022-05-08 16:55 UTC, EvilMadSquirrel commented
Во, спасибо! Фронт работы обеспечен :) Пока переключу опять в драфт.

2022-05-11 07:11 UTC, EvilMadSquirrel commented
> Сортировка не работает, потому что views переопределяют метод get_queryset родительского класса.

Вот тут случился затор. Пробовал без этого метода, тогда непонятно, как отфильтровать по контрибьютору, т.к. в корне класса нет объекта self. 
Еще пробовал в методе get_queryset присваивать в self.queryset нужный объект, а потом возвращать super().get_queryset() - получаю ошибку 'QuerySet' object has no attribute 'with_cte' из родительского класса.
Можно мне направляющий пинок?

2022-05-11 07:22 UTC, EvilMadSquirrel commented
> Сортировка не работает, потому что views переопределяют метод get_queryset родительского класса.

Вот тут случился затор. Пробовал без этого метода, тогда непонятно, как отфильтровать по контрибьютору, т.к. в корне класса нет объекта self. 
Еще пробовал в методе get_queryset присваивать в self.queryset нужный объект, а потом возвращать super().get_queryset() - получаю ошибку 'QuerySet' object has no attribute 'with_cte' из родительского класса. Вот из этого места:
![image](https://user-images.githubusercontent.com/36692278/167792230-4d42e745-f25c-4c23-8a02-73878b754116.png)
Можно мне направляющий пинок?

2022-05-11 07:27 UTC, antlu commented
https://github.com/Hexlet/hexlet-friends/blob/94274c07df425ccc88d05090c670b8cb973bdb1d/contributors/models/contribution.py#L13
Надо унаследовать от CTEManager.

2022-05-11 07:38 UTC, EvilMadSquirrel commented
Показалось, что нащупал решение, поэтому удалил коммент.

2022-05-11 07:44 UTC, EvilMadSquirrel commented
> https://github.com/Hexlet/hexlet-friends/blob/94274c07df425ccc88d05090c670b8cb973bdb1d/contributors/models/contribution.py#L13
> 
> Надо унаследовать от CTEManager.

Спасибо, помогло! Теперь нужно разобраться, как из contribution вытащить IssueInfo, что-то не соображу никак :)

2022-05-11 07:46 UTC, antlu commented
https://docs.djangoproject.com/en/3.2/topics/db/queries/#lookups-that-span-relationships

2022-05-16 06:10 UTC, EvilMadSquirrel commented on templates/contributor_issues.html
> +  {% include 'components/tables/contributor_issues.html' %}
Можно попросить помощь по этому пункту? Быстрый поиск выдал результат, что невозможно запихнуть две вьюхи в один шаблон. Как в общих чертах реализовывать три разных списка в одном шаблоне? На ум приходит только запихнуть ишьюсы и пуллреквесты внутрь вьюхи контрибьютора. Это вроде несложно :)

2022-05-17 06:35 UTC, EvilMadSquirrel commented on templates/contributor_details.html
> +            <h2 class="mr-5">{% trans "All-time contributions" %}</h2>
Вынес ссылки под карточку юзера :)

2022-05-17 19:49 UTC, antlu approved these changes

2022-05-20 06:23 UTC, merged