Add the ability to see activity on your group of projects (#183)
Hexlet/hexlet-friends pull request #195
Opened 2022-09-26 12:19 UTC by Dddarknight

2022-10-10 04:13 UTC, acidmaksim commented
@antlu Посмотришь?

2022-10-13 12:58 UTC, acidmaksim commented
@antlu посмотри, пожалуйста

2022-11-06 06:50 UTC, antlu requested changes

2022-11-06 06:50 UTC, antlu commented on contributors/models/project.py
> +    def contributors_count(self):
Комментариев и коммитов не хватает.

2022-11-07 09:40 UTC, Dddarknight commented
@antlu исправила, за искл тэгов - оставила их для сортировки

2022-11-13 09:16 UTC, antlu requested changes

2022-11-13 09:16 UTC, antlu commented on contributors/models/project.py
> +        ).get('count')
Расчёты лучше сделать в таком запросе.
```
repos = Repository.objects.filter(project=<project>).annotate(issues=Count('contribution', filter=Q(contribution__type='iss')), ...)
```

2022-11-14 19:20 UTC, Dddarknight commented
@antlu убрала лишние функции из модели, вся логика и расчеты теперь во view

2022-11-19 07:17 UTC, antlu approved these changes

2022-11-24 09:37 UTC, Dddarknight commented
мне что-то нужно сделать, чтобы убрать конфликт в миграциях? или это уже на стороне основного репо?

2022-11-24 09:41 UTC, acidmaksim commented
@antlu тыц

2022-11-25 22:54 UTC, antlu commented
Я бы изменил в имени файла миграции 9 на 10, а в dependencies указал предыдущий файл (0009_repository_owner_alter_repository_contributors_and_more).
Если не получится, можно выполнить команду, предлагаемую Django.

2022-11-26 09:36 UTC, Dddarknight commented
@antlu поправила

2022-11-26 09:50 UTC, antlu commented
https://github.com/Dddarknight/hexlet-friends/tree/main/contributors/migrations
В репозитории отсутствует файл 0009.
Можно выполнить rebase на ветку main текущего репозитория.

2022-11-26 10:50 UTC, merged