add page about project
Hexlet/hexlet-friends pull request #200
Opened 2022-10-18 18:32 UTC by ilnarkz

[#194] create page about project

2022-10-21 12:19 UTC, Malcom1986 commented
@ilnarkz Тут бы конфликт разрулить. А есть где-нибудь, например на Хероку, поднятый проект, результат посмотреть вживую?

2022-10-25 09:26 UTC, ilnarkz commented
> @ilnarkz Тут бы конфликт разрулить. А есть где-нибудь, например на Хероку, поднятый проект, результат посмотреть вживую?
@Malcom1986 Подскажи как их разрулить? Не могу победить

2022-10-28 13:51 UTC, ssssank commented
@ilnarkz а что не получается?

2022-10-28 14:33 UTC, ilnarkz commented
> @ilnarkz а что не получается?

@ssssank Да честно сказать уже не понимаю, локально то все работает. Сейчас не могу синхронизировать ветки, и решить конфликты. Когда эти конфликты появились в первый раз, пробовал подтянуть изменения, компилировал перевод заново и пушил, однако это так и не решило проблему с конфликтами.

2022-11-08 08:50 UTC, acidmaksim commented
@emp7yhead посмотри, пожалуйста

2022-11-08 15:44 UTC, emp7yhead requested changes

2022-11-08 15:44 UTC, emp7yhead commented on locale/ru/LC_MESSAGES/django.po
> +"Хекслета, анализируйте свой вклад, повышайте рейтинг и получайте 'ачивки'."
@acidmaksim Максим, тут бы посмотреть подойдет ли нам такое описание

2022-11-08 15:44 UTC, emp7yhead commented on templates/about.html
> +    </li>
Мне кажется, это лишнее - в футере уже имеется ссылка на исходный код. И надо добавить пустую строку в конце файла.

2022-11-08 15:48 UTC, acidmaksim commented on locale/ru/LC_MESSAGES/django.po
> +"Хекслета, анализируйте свой вклад, повышайте рейтинг и получайте 'ачивки'."
"Hexlet-friends - проект с открытым исходным кодом на Python. Сервис отслеживает опенсорсные проекты «Хекслета». Анализируется количество коммитов, пулл-реквестов, issue. Сервис автоматически строит рейтинг участников с «ачивками»."

Пока так, потом переделаем, если что

2022-11-08 16:22 UTC, ilnarkz commented on templates/about.html
> +    </li>
@emp7yhead Я поправил)

2022-11-08 17:32 UTC, emp7yhead approved these changes

2022-11-08 17:32 UTC, merged

2022-11-08 17:33 UTC, emp7yhead commented
@ilnarkz смержил