add tab groups to admin panel
Hexlet/hexlet-friends pull request #202
Opened 2022-11-03 19:33 UTC by kvazar941

2022-11-07 11:36 UTC, emp7yhead requested changes
Смотри на данный момент, чтобы добавить несколько пользователей необходимо удерживать “Control“ (или “Command“ на Mac). Если, например, будет группа на 20-30 человек это будет не совсем удобно. Можем сделать так, чтобы был удобный множественный выбор пользователей в группы?

2022-11-07 11:36 UTC, emp7yhead commented on .gitignore
> +settings.py
`.env` уже есть в гитигноре. `settings.py` не думаю, что следует сюда добавлять.

2022-11-07 11:36 UTC, emp7yhead commented on config/settings.py
> +    SECURE_SSL_REDIRECT = False #True
Данная настройка используется для перенаправления всех запросов с HTTP на HTTPS. Не стоит ее менять.

2022-11-09 06:40 UTC, kvazar941 commented
Добрый день!

Просмотрел, замечания понял - думаю, сегодня поправим. Так же попробую
сделать более удобный выбор пользователей внутри группы.

пн, 7 нояб. 2022 г., 14:36 Artyom Kropp ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Смотри на данный момент, чтобы добавить несколько пользователей необходимо
> удерживать “Control“ (или “Command“ на Mac). Если, например, будет группа
> на 20-30 человек это будет не совсем удобно. Можем сделать так, чтобы был
> удобный множественный выбор пользователей в группы?
> ------------------------------
>
> In .gitignore
> <https://github.com/Hexlet/hexlet-friends/pull/202#discussion_r1015302830>
> :
>
> > +env/
> +.env
> +settings.py
>
> .env уже есть в гитигноре. settings.py не думаю, что следует сюда
> добавлять.
> ------------------------------
>
> In config/settings.py
> <https://github.com/Hexlet/hexlet-friends/pull/202#discussion_r1015302945>
> :
>
> > @@ -23,7 +23,7 @@
>
>  if not DEBUG:
>      SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
> -    SECURE_SSL_REDIRECT = True
> +    SECURE_SSL_REDIRECT = False #True
>
> Данная настройка используется для перенаправления всех запросов с HTTP на
> HTTPS. Не стоит ее менять.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Hexlet/hexlet-friends/pull/202#pullrequestreview-1170221522>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWSYRPQ5B5FR7SZRHMFWKJLWHDSU3ANCNFSM6AAAAAARWPMFGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-23 11:59 UTC, emp7yhead reviewed
Все, теперь отлично выглядит, но обрати внимание на ошибки линтера. CI падает при проверке.

2022-11-28 10:35 UTC, Malcom1986 commented
@kvazar941 Нужна какая-то помощь?

2022-12-15 07:14 UTC, merged