issue #214: Compare your statistics with other users
Hexlet/hexlet-friends pull request #224
Opened 2022-12-28 13:08 UTC by yuriy-kormin

2023-01-10 08:48 UTC, emp7yhead commented
@yuriy-kormin посмотри ошибки линтера, пожалуйста

2023-01-19 11:56 UTC, acidmaksim commented
@yuriy-kormin тыц

2023-01-24 08:02 UTC, emp7yhead commented
@dzencot попрошу тебя посмотреть js?

2023-01-27 09:29 UTC, emp7yhead commented
@yuriy-kormin а ты где-нибудь разворачивал проект, чтобы можно было бы посмотреть?

2023-01-27 10:19 UTC, yuriy-kormin commented
только локально. ну можно попробовать docker образ собрать и залить на railway.
так а что там смотреть - в PR поправлен один файл, добавлен скрипт , остальное шаблоны

2023-01-27 10:29 UTC, dzencot requested changes

2023-01-27 10:29 UTC, dzencot commented on static/js/contrib_compare.js
> +  }else {
Тут нужен пробел после `{`

2023-01-27 10:29 UTC, dzencot commented on static/js/contrib_compare.js
> +    var json_data = $.parseJSON($('#contributors_data').text());
Вместо `var` везде лучше использовать `const`

2023-01-27 10:29 UTC, dzencot commented on static/js/contrib_compare.js
> +}
Нужно добавить пустую строку в конце файла. Это касается и других файлов где нет пустой строки

2023-01-27 12:57 UTC, emp7yhead commented
> только локально. ну можно попробовать docker образ собрать и залить на railway.

Давай на railway развернем, чтобы посмотреть как работают изменения

2023-02-01 06:12 UTC, yuriy-kormin commented
никак не получается собрать пакет на railway.  нужна помощь больно мудреная установка

2023-02-03 10:08 UTC, merged