impove 'make shell' to shell_plus extension using
Hexlet/hexlet-friends pull request #226
Opened 2022-12-29 17:32 UTC by yuriy-kormin

В курсе Хекслета [django-orm](https://ru.hexlet.io/courses/python-django-orm/lessons/setup/theory_unit) рекомендуется использовать shell_plus в качестве консоли django. [преимущества](https://django-extensions.readthedocs.io/en/latest/shell_plus.html) - модели и пользовательские классы загружаются автоматом при старте консоли

В пулл-реквест включены установка плагина и поправленный Makefile

2023-01-10 08:46 UTC, emp7yhead commented
@yuriy-kormin видимо забыл обновить poetry.lock, поэтому CI падает. Воспользуйся командой `poetry lock [--no-update]`

2023-01-14 04:40 UTC, yuriy-kormin commented
обновил poetry. lock

2023-01-20 11:54 UTC, emp7yhead requested changes

2023-01-20 11:54 UTC, emp7yhead commented on templates/open_issues_list.html
> +             data-bs-toggle="collapse"><b>{{ repo.full_name }}</b></a>
А как это связано с установкой shell_plus?

2023-01-20 11:54 UTC, emp7yhead commented on templates/open_issues_list.html
> +{% endblock %}
Это же не влияет на устанавливаемый shell_plus

2023-01-20 13:56 UTC, yuriy-kormin commented
прошу прощения - не тот коммит) сейчас поправлю

2023-01-20 15:26 UTC, closed without merging