search for members by organization #230
Hexlet/hexlet-friends pull request #251
Opened 2023-02-07 17:35 UTC by zhek111

Добавил поиск по организациям для участников

2023-02-08 08:38 UTC, acidmaksim commented
@zhek111 это какое issues?

2023-02-08 08:42 UTC, zhek111 commented
> 

230

2023-02-08 18:18 UTC, fey commented
@zhek111 привет, чтобы ишшус автоматом линковался с улл реквестом, вставляй ссылку или делай через решетку, например так #230 
Сделай плз демонстрацию, которую можно потыкать.

2023-02-08 18:21 UTC, zhek111 commented
@fey Демонстрация, это экран записать?

2023-02-08 18:47 UTC, fey commented
Нет, задеплоить на render.com или railway

2023-02-09 07:59 UTC, zhek111 commented
Я попробовал и там, и там, и через docker и без него. Окружение добавил. Postgres подключал. 
Не получается задеплоить сходу

2023-02-09 08:03 UTC, fey commented
Окей, @emp7yhead давай ручками посмотрим, покажешь мне, что там)

2023-02-20 10:52 UTC, dzencot commented
@fey @emp7yhead Тут получилось посмотреть?

2023-02-21 09:03 UTC, emp7yhead requested changes

2023-02-23 11:08 UTC, zhek111 commented on contributors/forms/forms.py
> +    )
Вроде бы сделал

2023-02-23 11:09 UTC, zhek111 commented on templates/contributors_list.html
> +</form>
Вроде бы сделал

2023-02-28 08:17 UTC, ashikov commented
@emp7yhead тут исправили, глянь, пожалуйста

2023-03-03 11:30 UTC, merged