Add filter form for contributors issue page
Hexlet/hexlet-friends pull request #282
Opened 2023-07-06 12:56 UTC by Dzigr

Добавлен фильтр по состоянию - селект со значениями, по статусам - открытые, закрытые, все (пустой инпут)

2023-07-10 10:25 UTC, ssssank commented
@Dzigr а сделай, пожалуйста, ссылочку, чтобы посмотреть на реальный результат

2023-07-10 10:58 UTC, Dzigr commented
@ssssank Выложил на render - [ссылка](https://hexlet-friends-aljz.onrender.com/contributors/mokevnin/issues/)

2023-07-10 11:00 UTC, fey commented
получится фильтр формы засунуть на ту же строку, Где поиск по названию и объединить формы? Тк по факту форма одна (поиск по названию и стейту)

2023-07-12 08:27 UTC, emp7yhead requested changes

2023-07-12 08:27 UTC, emp7yhead commented on requirements.txt
так, зависимости менять нет необходимости, это отдельно делаем

2023-07-12 08:27 UTC, emp7yhead commented on templates/contributor_issues.html
пустую строку в конце файла забыл

2023-07-12 08:27 UTC, emp7yhead commented on contributors/views/contributor_issues.py
> +            return queryset
А зачем нам отказываться от вызова `get_queryset()` из родительского класса? Посмотри в `TableSortSearchMixin`, что он делает. Если его не вызвать, то мы лишаемся возможности сортировать результаты по полям таблицы.

2023-07-12 18:39 UTC, Dzigr commented on requirements.txt
Могу данный коммит отменить, но тогда на рендер результат выложить не получается.

2023-07-12 18:44 UTC, Dzigr commented
Результат получается такой: 
![изображение](https://github.com/Hexlet/hexlet-friends/assets/109955706/8fb7566b-3385-4867-b477-186e1b833214)
Соответственно с двумя категориями на выбор - open / close
Единственный вопрос относительно добавления перевода для фильтра - стоит ли это делать или это потом будет отдельный issue?

2023-07-13 02:38 UTC, emp7yhead commented on requirements.txt
а, все, тогда вопрос снят)

2023-07-13 13:09 UTC, Dzigr commented
Форму финализировал, перевод добавил, комментарии выше учел

2023-07-14 04:27 UTC, emp7yhead commented
@Dzigr все шикарно, но осталось победить линтер )

2023-07-14 09:18 UTC, Dzigr commented
@emp7yhead Запушил изменения с фиксами линтера )

2023-07-18 05:50 UTC, merged

2023-07-18 05:51 UTC, emp7yhead commented
@Dzigr Спасибо!