Added filter for issues, issue#166
Hexlet/hexlet-friends pull request #284
Opened 2023-07-16 21:51 UTC by SvetlanaAkaemova

Added filter for issue by label good_first_issue and by title and repository name.

2023-07-17 08:23 UTC, ssssank commented
Было бы здорово задеплоить вашу работу, чтобы была возможность потыкать в эти фильтры и проверить результат :)

2023-07-17 08:28 UTC, SvetlanaAkaemova commented
Это как делается?) Просто как проект на Railway задеплоить?

2023-07-17 08:34 UTC, ssssank commented
Да, также (почти) как учебные проекты. Можно попробовать по этой инструкции: https://github.com/Hexlet/hexlet-friends/blob/main/DEPLOYMENT.md

Также можно попробовать сервис render.com, для него инструкции пока нет, но если получится, можно эту инструкцию сделать и закинуть отдельным ПР

2023-07-17 22:37 UTC, SvetlanaAkaemova commented
https://hexlet-friends-my-new-feature.onrender.com/issues
Развернула на рендере. Вопрос про заполнение данными. Вы сможете добавить issues для проверки или я это могу как-то сделать?

2023-07-18 08:21 UTC, ssssank commented
В инструкции для railway есть такой пункт, нужно попробовать выполнить эту же команду и в твоём окружении:

> Если необходимо выполнить заполнение БД, то в Start Command следует указать команду python manage.py fetchdata <organization name>

2023-07-18 12:44 UTC, SvetlanaAkaemova commented
Не получается пока. Есть ли ещё способы?

2023-07-18 14:41 UTC, fey commented
@SvetlanaAkaemova вы можете у себя на локальном компе изменить креды подключения к базе данных. Указать БД которая указана в рейлвее/рендере. И выполнить команду локально.

2023-07-18 15:06 UTC, SvetlanaAkaemova commented
Сделала через pgadmin4. Теперь там есть мои тестовые данные. Вроде работает:
https://hexlet-friends-my-new-feature.onrender.com/issues

2023-07-18 15:10 UTC, fey commented
https://hexlet-friends-my-new-feature.onrender.com/issues?info__title=&repository__full_name=&label_group=0

ошибочка

2023-07-18 15:12 UTC, SvetlanaAkaemova commented
Label group не фильтруют пока нет групп. Я уточняла этот вопрос. Здесь этот фильтр просто как пример. Работать должны только good_first_issue и по названиям

2023-07-18 15:14 UTC, fey commented
Так, а что с этим инпутом будем делать? На проде он будет работать? Представьте пользователя, который будет нажимать кнопки на этой форме, а тут что-то сломается )

2023-07-18 15:35 UTC, Shvidunov commented
Фильтрики работают. На первый взгляд есть проблема с расположением полей фильтров (android 12, pixel 3)
![Screenshot_20230718-182524](https://github.com/Hexlet/hexlet-friends/assets/121935818/97d1779c-1962-42d4-a353-876f3d583020)
Надпись label group не на месте как мне кажется.

2023-07-18 15:36 UTC, Shvidunov commented
В версии RU  частично на английском верхнее поле поиска

2023-07-18 17:05 UTC, fey commented
Ребята тестировщики тестируют ваш код (демо), поэтому можно их замечания тоже смотреть и править

2023-07-18 17:13 UTC, SvetlanaAkaemova commented
Да, я читаю.) Сегодня поправлю стили и переводы. Если что, я напишу)

2023-07-18 20:27 UTC, AavadaKedavra commented
наименования в строках поиска нужно вводить полностью, иначе ничего не находит 
![image](https://github.com/Hexlet/hexlet-friends/assets/126116401/9b850498-05cc-44ee-ab9e-554bf8991392)
![image](https://github.com/Hexlet/hexlet-friends/assets/126116401/4848a13b-2c0e-4767-82fb-0aad8a30634a)
![image](https://github.com/Hexlet/hexlet-friends/assets/126116401/56c6874d-30f7-4d70-abd3-7500aad8ad87)
![image](https://github.com/Hexlet/hexlet-friends/assets/126116401/5f948f78-e1e2-45de-89a9-dc177c811a13)

2023-07-19 04:57 UTC, Shvidunov commented
Вопрос. Должна ли быть регистрозависимость в поиске? Название строчными находит, с заглавной не находит.
![Screenshot_20230719-075510](https://github.com/Hexlet/hexlet-friends/assets/121935818/e026c23a-0fbb-4e75-b1e5-5cb9be0ef6bf)
![Screenshot_20230719-075449](https://github.com/Hexlet/hexlet-friends/assets/121935818/bb3c1a9d-f5e3-4a8d-b79a-79bb3c690d32)

2023-07-19 09:24 UTC, fey commented
а github позволяет создать репозитории с одинаковым названием, но в разном регистре? Если нет, То поиск должен быть регистронезависим.

2023-07-19 22:21 UTC, SvetlanaAkaemova commented
https://hexlet-friends-my-new-feature.onrender.com/issues

Добавила фильтр по языку (по нему ведь наверно тоже хорошо искать)
Сделала фильтры с icontains, поставила в ряд (насколько это удобно для мобильной версии?)
Добавила crispy для полей
Переводы поправила.
Жду замечания)

2023-07-21 14:15 UTC, ssssank commented
@fey @emp7yhead посмотрите, пожалуйста

2023-07-21 14:43 UTC, fey commented
По внешнему виду - ок, если что можно поправить. 
По коду надо ревью @emp7yhead или @sgmdlt

2023-07-25 05:01 UTC, emp7yhead commented
@fey тут используется django-filters, хотя мы используем самостоятельно написанную реализацию фильтрации. Оставляем?

2023-07-25 08:28 UTC, fey commented
да, давай оставим. 
А почему мы использовали свои фильтры? :)

2023-07-25 08:54 UTC, emp7yhead commented
> А почему мы использовали свои фильтры? :)
Потому что можем :)

2023-07-25 09:00 UTC, fey commented
Если мы пишем свой код, то его надо поддерживать. А если используем библиотеку, готовое решение, то отдаем это на откуп другим разработчикам.

Можно и джанго не использовать, а писать все самому :) :) :)

2023-07-25 09:32 UTC, emp7yhead requested changes
Плюс посмотри, у тебя возник конфликт, надо его устранить и не забудь прогнать линтер

2023-07-25 11:30 UTC, SvetlanaAkaemova commented on config/settings.py
> +)
Это у меня не работало что-то, я проверяла, что может из-за вот этих строк. Это я всё поправлю как было

2023-07-25 13:46 UTC, SvetlanaAkaemova commented
Я не знаю, правильно ли это, но я поправила всё как в исходном requirements.txt ( плюс там django-filters добавлен).
Исправила замечания выше ( в settings и contrib_extras)
Но у меня всё равно конфликт. Скажите пожалуйста, как это исправляется?
Ещё с линтером проблема, т к у меня выходит ошибка с плагином flake8-bandit

2023-07-27 06:14 UTC, fey commented
@SvetlanaAkaemova потестировали ваш ПР, выяснили, что ломается загрузка свежих данных. Почему - непонятно.

Пока предлагаю убрать django filters. Ищщус https://github.com/Hexlet/hexlet-friends/issues/291

2023-07-27 06:33 UTC, fey commented
django filters оставляем @emp7yhead напишет, что нужно поправить. 
После правок - еще раз чекнем и поможем с конфликтами.

2023-07-27 06:36 UTC, emp7yhead requested changes

2023-07-27 06:36 UTC, emp7yhead commented on contributors/models/issue_info.py
> +        return self.title
Строковое представление не следует менять - это ломает поведение при загрузке данных с гитхаба

2023-07-27 06:36 UTC, emp7yhead commented on contributors/models/repository.py
> +        return self.full_name
Тут тоже самое

2023-07-27 10:21 UTC, fey commented
@SvetlanaAkaemova поправьте, пожалуйста, замечания линтера.
Я пересобрал вашу ветку и форспушнул. Вы можете сделать хард ресет, чтобы получить изменения
Находясь в своей ветке - 

```bash
$ git reset --hard origin/my-new-feature
```

Только следдующий коммит делайте отдельный, без форс пуша.

2023-07-30 20:47 UTC, SvetlanaAkaemova commented
Я поправила код и хочу запушить изменения. Подскажите пожалуйста, как это сделать грамотно, чтоб не поломать ничего. Я хотела сделать отдельный коммит, но выходит ошибка. Пришлось откатиться. Сейчас у меня изменения без коммита ждут команду.
<img width="1398" alt="Снимок экрана 2023-07-30 в 22 41 13" src="https://github.com/Hexlet/hexlet-friends/assets/105640480/b4aab548-5300-4687-b470-c9c7bf027514">

2023-07-31 08:25 UTC, ola-9 commented
@SvetlanaAkaemova ворфлок упал, нужно поправить. Посмотрите, пожалуйста.

2023-07-31 08:56 UTC, fey commented
@SvetlanaAkaemova 
>Я поправила код и хочу запушить изменения. Подскажите пожалуйста, как это сделать грамотно, чтоб не поломать ничего. Я хотела сделать отдельный коммит, но выходит ошибка. Пришлось откатиться. Сейчас у меня изменения без коммита ждут команду.

смотрите, я в вашу ветку запушил код, т.е. ваша вашей локальной ветке нет нужного коммита. Самый простой вариант это сделать хард-ресет `git reset --hard origin/my-new-feature` - вы выполнили эту команду? Скорее всего перед этим нужно будет сделать `git fetch`

2023-07-31 11:33 UTC, SvetlanaAkaemova commented
Да, я в моей ветке сделала reset,  потом внесла правки и закоммитила, вышла ошибка. 
Т.е мне теперь сделать fetch, reset, а потом правки и коммит, верно?

2023-07-31 11:47 UTC, fey commented
а подскажите, что у вас выводится в коммитах? `git log`, интересует что в нескольких последних коммитах. В теории можно форспушнуть.

2023-07-31 12:50 UTC, SvetlanaAkaemova commented
Я пушила одним коммитом всегда, просто внося правки. Вот последние 5 коммитов  с моим одним
<img width="1204" alt="Снимок экрана 2023-07-31 в 14 47 42" src="https://github.com/Hexlet/hexlet-friends/assets/105640480/d31924a9-b210-4781-bb86-2b482dd3131f">

2023-07-31 12:52 UTC, SvetlanaAkaemova commented
И я уже тут писала про проблему с линтером. У меня ругается flake8 на плагин bandit. Ошибки линтера я подсмотрела в actions. Но не уверена, что сейчас всё исправлено, и ошибок нет. Можно же будет глянуть опять , что не на месте?

2023-07-31 12:55 UTC, SvetlanaAkaemova commented
Тогда я пушну в тот же, как раньше, да?

2023-07-31 13:14 UTC, SvetlanaAkaemova commented
Ну да, опять конфликты. Что-то не ладится с моим пулл реквестом(

2023-08-02 07:54 UTC, fey commented
@SvetlanaAkaemova я разрешил конфликты и смержил в вашу ветку изменения. 
Сделайте git pull и посмотрите замечания линтера.

2023-08-02 08:20 UTC, SvetlanaAkaemova commented
Нужно ли что-то делать перед исправлением? 
git fetch  и git reset.

2023-08-02 08:34 UTC, fey commented
Фетч можно, ресет не надо. Не забудьте запушить новым коммитом, не изменяя старый. Ничего страшного, что в вашей ветке получилось несколько коммитов. Главное пока историю коммитов не менять.

2023-08-02 08:35 UTC, fey commented
Фетч можно, ресет не надо. Не забудьте запушить новым коммитом, не изменяя старый. Ничего страшного, что в вашей ветке получилось несколько коммитов. Главное пока историю коммитов не менять.

2023-08-02 19:57 UTC, SvetlanaAkaemova commented
Прежде чем вносить изменения, я всё же уточню. После git pull вышло это. Я в сомнениях, стоит ли еще дополнительно вводить команды, или всё, что должно было распаковаться, распаковалось?
<img width="1077" alt="Снимок экрана 2023-08-02 в 21 53 39" src="https://github.com/Hexlet/hexlet-friends/assets/105640480/325bb4a6-ade0-4599-81df-06bec0221ff0">

2023-08-03 10:18 UTC, fey commented
@SvetlanaAkaemova сделайте `git pull origin my-new-feature` и покажите историю коммитов в `git log`

2023-08-03 11:33 UTC, SvetlanaAkaemova commented
Сделала. Вот последние 5 коммитов
<img width="990" alt="Снимок экрана 2023-08-03 в 13 31 16" src="https://github.com/Hexlet/hexlet-friends/assets/105640480/e44117b6-5ac7-4a40-92dd-0925d81b428f">

2023-08-03 14:48 UTC, fey commented
да, выглядит хорошо. Попробуйте теперь запушить изменения.

2023-08-03 20:35 UTC, SvetlanaAkaemova commented
Поправила ошибки линтера из actions. Надеюсь, теперь всё в порядке. Закомменченный фильтр по группам лейблов убрала совсем, чтоб никого не путать им.

2023-08-04 11:47 UTC, fey commented
@SvetlanaAkaemova тут снова падает на линтере. Попробуйте поправить, если будут вопросы. задавайте

2023-08-04 14:05 UTC, SvetlanaAkaemova commented
Исправила. А файл github_lib.py я вроде не трогала. Ругается на него тоже.

2023-08-04 14:36 UTC, fey commented
Это нормально, возможно появились новые правила линтера. ПОпробуйте посмотреть замечания.

2023-08-04 14:52 UTC, SvetlanaAkaemova commented
Попытка номер 1)
Добавила timeout

2023-08-07 10:28 UTC, merged

2023-08-07 11:28 UTC, SvetlanaAkaemova commented
Сейчас выходит серверная ошибка 500 при фильтрации. Это в коде моем ошибка где-то?

2023-08-07 12:23 UTC, fey commented
Возможно)

2023-08-07 13:21 UTC, fey commented
Давайте попросим @sgmdlt посмотреть.
Но может оказаться, что у нас и логи не пишутся :(

2023-08-10 08:01 UTC, SvetlanaAkaemova commented
Сейчас проблема осталась только с good first issue фильтром. Остальное вроде заработало. Как я вижу, открытых проблем с этим лейблом сейчас нет. Может в этом проблема. Хотя я потестила у себя такой случай, и просто пустой список выходит.

2023-08-10 08:28 UTC, fey commented
@SvetlanaAkaemova можете завести баг-репорт?)

2023-08-10 08:42 UTC, SvetlanaAkaemova commented
Попробую. А на рейлвее не видны эти ошибки?

2023-08-10 09:05 UTC, fey commented
Между рендером и рейлвеем, как и хероку (где у нас продакщен) не должно быть большой разницы. 

Вы можете сейчас завести багрепорт, что при таких-то условиях срабатывет 500, а локально нет. Плюс можно отдельно проверить, подключены ли у нас сборщики ошибок. Раньше мы активно использовали rollbar. Сейчас переходим на sentry. Пожалуй, заведу на это ищщус)